language: node_js
addons:
  chrome: stable
branches:
  only:
    - "master"
node_js:
  - "12.8.0"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
script:
  - npm run generate-import-map
  - npm run eslint-check
  - npm run prettier-check
  - npm run test-with-coverage
  # - npm run generate-lighthouse-report
after_success:
  - npm run upload-coverage
  # - node ./script/update-lighthouse-pr-comment-from-travis.js
