language: node_js
branches:
  only:
    - "master"
node_js:
  - "12.8.0"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
script:
  - npm run generate-import-map
  - npm run eslint-check
  - npm run prettier-check
  - npm run generate-coverage
  - npm run generate-lighthouse-report
after_success:
  - npm run upload-coverage
  - node ./script/update-pull-request-lighthouse-report/update-pull-request-lighthouse-report.js
