coverage:
  # I like coverage but I think it should not be enforced
  # so force coverage status to be always green
  range: 0...100
  status:
    project:
      default:
        # same idea about coverage being nice to have:
        # a commit/pr decreasing coverage is still successful not matter how much
        # it decreases coverage
        threshold: 100
  parsers:
    javascript:
      enable_partials: yes

comment:
  layout: "header"
  behavior: default
