name: size-impact

on:
  pull_request:
    # In theory it would be more efficient to enable this workflow only
    # if certain file changes (the one that could impact dist/ files)
    # In practice humans will wonder why the workflow did not run.
    # paths:
    #   - "index.js"
    #   - "src/**"

jobs:
  size-impact:
    # Do not run this workflow on forks because they are not authorized to post comments, see links below:
    # https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token
    # https://github.community/t5/GitHub-Actions/Token-permissions-for-forks-once-again/td-p/33839
    # https://github.com/WordPress/gutenberg/issues/17324
    if: github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [13.12.0]
    runs-on: ${{ matrix.os }}
    name: size impact
    env:
      CI: true
    steps:
      - name: Setup git
        env:
          GITHUB_REPOSITORY_URL: ${{ github.repositoryUrl }}
        run: |
          git init
          git remote add origin $GITHUB_REPOSITORY_URL
      - name: Setup node  ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup npm
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Git checkout base
        run: |
          git fetch --no-tags --prune --depth=1 origin $GITHUB_BASE_REF
          git checkout origin/$GITHUB_BASE_REF
          git log -1
      # Please note || echo "{}" > ../snapshot.base.json
      # It means we fallback on an empty snapshot when left command fails.
      # It exists in case the base branch does not contains size-impact files.
      # Happens at least when a pull request introduces
      # @jsenv/github-pull-request-filesize-impact to a repository for the first time.
      - name: Generate snapshot for base
        run: |
          npm install
          npm run dist
          node ./.github/workflows/size-impact/generate-size-snapshot.js ../snapshot.base.json || echo "{}" > ../snapshot.base.json
      - name: Git merge head
        # Here we must fetch $GITHUB_REF and not $GITHUB_HEAD_REF because
        # $GITHUB_HEAD_REF might come from a fork
        run: |
          git fetch --no-tags --prune origin $GITHUB_REF
          git merge FETCH_HEAD
      - name: Generate snapshot after merge
        run: |
          npm install
          npm run dist
          node ./.github/workflows/size-impact/generate-size-snapshot.js ../snapshot.head.json
      - name: Report size impact
        run: node ./.github/workflows/size-impact/report-size-impact.js ../snapshot.base.json ../snapshot.head.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
